name: sage_easypqp_library
description: Runs SAGE searches (DDA and optional DIA), combines results, converts to EasyPQP pickles and builds an EasyPQP library (transition TSV / PQP). Exposes per-run run_peaks output for downstream per-run iRT generation.
keywords:
  - sage
  - easypqp
  - library
input:
  - DDA_FOR_SEARCH:
      type: channel
      description: Channel of DDA input tuples (as produced by the main workflow).
  - DIA_FOR_SEARCH:
      type: channel
      description: Channel of DIA input tuples for optional DIA-based library building. Can be empty.
  - fasta_ch:
      type: file
      description: Fasta file used for SAGE searches.
      pattern: "*.fa*"
output:
  - library_tsv:
      type: file
      description: EasyPQP transition TSV produced by EasyPQP library step.
      pattern: "easypqp_library.tsv"
  - run_peaks:
      type: file
      description: Per-run peak lists produced by EasyPQP which can be used as run-specific iRT inputs (pattern: *_run_peaks.tsv).
      pattern: "*_run_peaks.tsv"
  - psmpkl:
      type: file
      description: PSM pickle files generated by EASYPQP_CONVERTSAGE.
      pattern: "*.psmpkl"
  - peakpkl:
      type: file
      description: Peak pickle files generated by EASYPQP_CONVERTSAGE.
      pattern: "*.peakpkl"
  - sage_results:
      type: file
      description: Combined SAGE results TSV (joined results + matched fragments).
      pattern: "*.tsv"
authors:
  - "@singjc"
